const {Url} = require('../models/urlshorten');
const mongoose = require('mongoose');
const express = require('express');
const router = express.Router();
const ids = require('short-id');

ids.configure({
    length: 5
});

router.get('/:id', async (req, res) => {
    const url = await Url.findOne({
        ShortId: req.params.id
    });
    res.writeHead(301, {
        Location: url.inputUrl
    });
    res.end();
});

// Stats

router.get('/stats/:id', async (req, res) => {
    const url = await Url.findOne({
        ShortId: req.params.id
    });
    res.json({
        'Redirect to' : url.inputUrl,
        'Created at ': url.createdAt,
        'Generated By' : url.createdBy,
        'Shortlink ': url.ShortId
    });

})

// Custom Url
router.get('/:id/:custom', async(req,res)=>{
    const url = await Url.findOne({
        ShortId: req.params.id
    })
    url.ShortId = req.params.custom;
    await url.save();
    res.writeHead(301, {
        Location: url.inputUrl
    });
    res.end();
})

router.post('/transfer', async (req, res) => {
    const input = req.body.inputUrl;
    const short = ids.store(input);

    let url = await Url.findOne({
        inputUrl: input
    });
    if (url) {
        url.createdBy++;
        await url.save();
        console.log('Already exits : ', url);
        return res.send(url);
    }

    url = new Url({
        inputUrl: input,
        ShortId: short,
        createdBy: 1
    });

    await url.save();
    res.send(url);
    console.log('Created New : ', url);
});

module.exports = router;